image: golang:latest

variables:
  REPO_NAME: gitlab.com/ddb_db/piawgcli

before_script:
  - go version
  - echo $CI_BUILD_REF
  - echo $CI_PROJECT_DIR

stages:
  - test
  - build
  - release
  
test-project:
  stage: test
  script:
    - mkdir -p $GOPATH/src/$REPO_NAME
    - cp -r $CI_PROJECT_DIR/* $GOPATH/src/$REPO_NAME
    - cd $GOPATH/src/$REPO_NAME
    - go test $(go list ./... | grep -v /vendor/)
    
build-project:
  stage: build
  script:
    - OUTPUT="piawgcli"
    - mkdir -p $GOPATH/src/$REPO_NAME
    - cp -r $CI_PROJECT_DIR/* $GOPATH/src/$REPO_NAME/
    - cd $GOPATH/src/$REPO_NAME/cmd/piawgcli
    - bash $CI_PROJECT_DIR/build-all.sh $OUTPUT $CI_PROJECT_DIR
    
  artifacts:
    paths:
      - artifacts/

release:
  only:
    variables:
      - $CI_COMMIT_TAG =~ /^v\d+\./
  stage: release
  script:
    - cd $CI_PROJECT_DIR/artifacts
    - 'find * -type f -name \*.gz -exec curl -f --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file {} ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/piawgcli/${CI_COMMIT_TAG}/{} \;'